apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cm9vdAo=   # 编码: echo 'root' | base64
  mongo-root-password: cm9vdAo=   # 解码: echo 'cm9vdAo=' | base64 --decode
