apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: c3VraW14MTIzNA==

#echo -n "root" | base64
#echo -n "sukimx1234" | base64     echo -n "c3VraW14MTIzNA==" | base64 --decode

#mongo --port 27017 -u "root" -p "sukimx1234" --authenticationDatabase "admin"